name: Full Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" #Her gün sabah 6:00'da çalışır
jobs:
  smoke-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run Smoke Tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --env grep=@Smoke
        env:
          APP_USERNAME: ${{ vars.APP_USERNAME}}
          APP_PASSWORD: ${{ vars.APP_PASSWORD}}

      - name: Upload Smoke Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Smoke Report
          path: cypress/reports/html/Smoke_index.html
          if-no-files-found: ignore

      - name: Deploy Smoke Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: cypress/reports/html
          destination_dir: smoke
          
      - name: Add Smoke Link to Summary
        if: always()
        run: |
          echo "### 🚀 Smoke Report" >> $GITHUB_STEP_SUMMARY
          echo "[View Smoke Report](https://volkantutunculer.github.io/pedogist.com_test/smoke/index.html)" >> $GITHUB_STEP_SUMMARY

  regression-tests:
    needs: smoke-tests
    if: success()
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Run Regression Tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --env grep=@Regression
        env:
          APP_USERNAME: ${{ vars.APP_USERNAME}}
          APP_PASSWORD: ${{ vars.APP_PASSWORD}}

      - name: Upload Regression Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Regression Report
          path: cypress/reports/html/Regression_index.html
          if-no-files-found: ignore

      - name: Deploy Regression Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: cypress/reports/html
          destination_dir: regression

      - name: Add Regression Link to Summary
        if: always()
        run: |
          echo "### 📊 Regression Report" >> $GITHUB_STEP_SUMMARY
          echo "[View Regression Report](https://volkantutunculer.github.io/pedogist.com_test/regression/index.html)" >> $GITHUB_STEP_SUMMARY
