name: End-to-end tests

on:
  push:
  schedule:
    - cron: "0 10 * * 1" # Run every Monday at 6:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run

      - name: Upload Cypress Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Reports
          path: cypress/reports/html/index.html
          if-no-files-found: ignore

      - name: Deploy Reports
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports/html

      - name: Add Report Link to Summary
        if: always()
        run: |
          echo "### 📊 Cypress Test Report" >> $GITHUB_STEP_SUMMARY
          echo "[View Report](https://volkantutunculer.github.io/pedogist.com_test/index.html)" >> $GITHUB_STEP_SUMMARY
